# Generated by Django 6.0.6 on 2026-06-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Design', 'Design'), ('Product', 'Product'), ('Sales', 'Sales & Ops')], max_length=50)),
                ('location', models.CharField(default='Remote', max_length=100)),
                ('job_type', models.CharField(default='Full-time', max_length=50)),
                ('blurb', models.TextField(help_text='One-line summary shown on the role card.')),
                ('responsibilities', models.TextField(help_text='One item per line.')),
                ('requirements', models.TextField(help_text='One item per line.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the careers page.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=300)),
                ('note', models.CharField(blank=True, help_text='Reminder of where this is used.', max_length=200)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Homepage'), ('careers', 'Careers page')], default='home', max_length=20)),
                ('value', models.CharField(help_text='e.g. "40", "99.9", "24"', max_length=20)),
                ('suffix', models.CharField(blank=True, help_text='e.g. "+", "%", "/7"', max_length=10)),
                ('label', models.CharField(help_text='e.g. "Agents in production"', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(help_text='e.g. "Director of Operations"', max_length=100)),
                ('detail', models.CharField(blank=True, help_text='e.g. "Logistics & freight"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
