# Generated by Django 5.2.2 on 2026-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_jobposting_apply_url_alter_jobposting_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('project_type', models.CharField(blank=True, help_text='e.g. AI agent, enterprise platform, workflow automation, integration.', max_length=160)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('timeline', models.CharField(blank=True, max_length=120)),
                ('budget_range', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(help_text='AI-generated or user-submitted project summary.')),
                ('business_problem', models.TextField(blank=True)),
                ('desired_outcome', models.TextField(blank=True)),
                ('current_tools', models.TextField(blank=True, help_text='Current software, systems, APIs, databases, or workflows.')),
                ('conversation', models.TextField(blank=True, help_text='Full chatbot conversation/context submitted by the user.')),
                ('source', models.CharField(choices=[('chatbot', 'Chatbot'), ('contact_form', 'Contact Form'), ('manual', 'Manual')], default='chatbot', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed')], default='new', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('page_url', models.URLField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Inquiry',
                'verbose_name_plural': 'Project Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Job Posting', 'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['key'], 'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='sitestat',
            options={'ordering': ['page', 'order'], 'verbose_name': 'Site Stat', 'verbose_name_plural': 'Site Stats'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitestat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
